[package]
name = "rummage"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-version = "0.3.5"
raw-cpuid = "10.7.0"
sys-info = "0.9.1"
tracing = "0.1.37"

[build-dependencies]
rustc_version = "0.4.0"
