[package]
name = "rummage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bosion = "1.0.0"
tracing = "0.1.37"

[build-dependencies]
bosion = "1.0.0"
